export const bookmarks = [
  {
    _id: "post1",
    content: "Roadmap to become a full stack web3 developer in 180 days.",
    images: ["https://picsum.photos/id/1/800/600"],
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-05-16T13:00:21+05:30",
    updatedAt: "2022-05-16T13:00:21+05:30",
    comments: [],
    id: "1",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post2",
    content:
      "Love the idea behind this. A clear goal and how to achieve it. I believe as you go, you would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-11T13:00:21+05:30",
    updatedAt: "2022-06-11T13:00:21+05:30",
    comments: [],
    id: "2",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post3",
    content: "A clear goal and how to achieve it",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-04-16T13:00:21+05:30",
    updatedAt: "2022-04-16T13:00:21+05:30",
    comments: [],
    id: "3",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post4",
    content:
      "I believe as you go, you would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-05-24T13:00:21+05:30",
    updatedAt: "2022-05-24T13:00:21+05:30",
    comments: [],
    id: "4",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post5",
    content:
      "Love the idea behind this. You would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-05T13:00:21+05:30",
    updatedAt: "2022-06-05T13:00:21+05:30",
    comments: [],
    id: "5",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post6",
    content:
      "A clear goal and how to achieve it. I believe as you go, you would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-01T13:00:21+05:30",
    updatedAt: "2022-06-01T13:00:21+05:30",
    comments: [],
    id: "6",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post7",
    content:
      "You would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-03-18T13:00:21+05:30",
    updatedAt: "2022-03-18T13:00:21+05:30",
    comments: [],
    id: "7",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post15",
    content:
      "And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "8",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post8",
    content: "Wish you the best!👍🏾",
    images: null,
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "9",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post9",
    content: "Love the idea behind this",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "10",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post10",
    content:
      "I believe as you go, you would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "11",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post11",
    content:
      "A clear goal and how to achieve it. I believe as you go, you would realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
      ],
      dislikedBy: [],
    },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "12",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post12",
    content:
      "Realize that you need more time with some. And sometimes, I may intend to spend selected hours learning but end up spending more. Wish you the best!👍🏾",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "joweltisso",
    firstName: "Jowel",
    lastName: "Tisso",
    userId: "jowel123",
    avatar: "https://i.pravatar.cc/150?img=60",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "13",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post13",
    content: "Love the idea behind this",
    images: null,
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "jowel123",
          firstName: "jowel",
          lastName: "tisso",
          username: "joweltisso",
          password: "test123",
          bookmarks: [],
          createdAt: "2022-05-18T16:24:10+05:30",
          updatedAt: "2022-05-18T16:24:10+05:30",
          followers: [],
          following: [],
          id: "1",
        },
        {
          _id: "goku123",
          createdAt: "2022-05-18T16:35:54+05:30",
          updatedAt: "2022-05-18T16:35:54+05:30",
          username: "songoku",
          password: "goku",
          firstName: "Son",
          lastName: "Goku",
          email: "goku@gmail.com",
          followers: [],
          following: [],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "14",
    bookmarkUserId: "jowel123",
  },
  {
    _id: "post14",
    content:
      "I believe as you go, you would realize that you need more time with some👍🏾",
    images: null,
    likes: { likeCount: 0, likedBy: [], dislikedBy: [] },
    username: "songoku",
    firstName: "Son",
    lastName: "Goku",
    userId: "goku123",
    avatar: "https://i.pravatar.cc/150?img=54",
    createdAt: "2022-06-16T16:19:49+05:30",
    updatedAt: "2022-06-16T16:19:49+05:30",
    comments: [],
    id: "15",
    bookmarkUserId: "jowel123",
  },
];
